apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
    matchExpressions:
      - { key: team, operator: In, values: [team1] }
      - { key: tier, operator: In, values: [frontend] }
      - { key: team, operator: In, values: [team1, team2] }
  template:
    metadata:
      name: "webpod4"
      labels:
        env: prod
        team: team1
        tier: frontend
    spec:
      containers:
      - name: "webrc1"
        image: "vimal13/apache-webserver-php"
